
FROM nvcr.io/nvidia/merlin/merlin-tensorflow:22.09

WORKDIR /

# RUN pip install -U pip
RUN pip install git+https://github.com/NVIDIA-Merlin/models.git@efe4bc91cc7e161f6e1c6dab3ff2a8ef04fd84b5 gcsfs google-cloud-aiplatform fastapi


COPY trainer /trainer
# COPY trainer/* ./

# RUN pip install -r trainer/requirements.txt

# CMD python trainer/task.py
