
FROM nvcr.io/nvidia/merlin/merlin-tensorflow:22.12

WORKDIR / 

COPY /serving/requirements.txt /requirements.txt

RUN pip install -r /requirements.txt

COPY /serving/app /app

EXPOSE 80
    
CMD ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port $AIP_HTTP_PORT"]
